import React, { createContext, useContext, useState } from 'react';

type Language = 'en' | 'sw';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navigation
    home: 'Home',
    about: 'About',
    services: 'Services',
    contact: 'Contact',
    login: 'Login',
    logout: 'Logout',
    
    // Hero
    heroTitle: 'Empowering Safer Drivers',
    heroSubtitle: 'Welcome to Dereva Kiganjani',
    heroDescription: 'Your one-stop platform for driver services, license management, testing, and learning',
    
    // Services
    leseni: 'Leseni',
    leseniDesc: 'License Services',
    jiTesti: 'JiTesti',
    jiTestiDesc: 'Driver Test',
    elimika: 'Elimika',
    elimikaDesc: 'Driver Learning',
    ajiraYaUdereva: 'Ajira ya Udereva',
    ajiraDesc: 'Driver Jobs',
    ajiriDereva: 'Ajiri Dereva',
    ajiriDesc: 'Hire a Driver',
    
    // Common
    getStarted: 'Get Started',
    learnMore: 'Learn More',
    submit: 'Submit',
    cancel: 'Cancel',
    save: 'Save',
    continue: 'Continue',
    back: 'Back',
    next: 'Next',
    
    // Dashboard
    welcome: 'Welcome',
    dashboard: 'Dashboard',
    myProfile: 'My Profile',
    myResults: 'My Results',
    notifications: 'Notifications',
    recentActivity: 'Recent Activity',
    
    // Test
    startTest: 'Start Test',
    selectCategory: 'Select Vehicle Category',
    paymentMethod: 'Payment Method',
    testInProgress: 'Test in Progress',
    submitAnswer: 'Submit Answer',
    correct: 'Correct',
    incorrect: 'Incorrect',
    passed: 'PASSED',
    failed: 'FAILED',
    retakeTest: 'Retake Test',
    downloadCertificate: 'Download Certificate',
    
    // Profile
    fullName: 'Full Name',
    phoneNumber: 'Phone Number',
    nationalId: 'National ID',
    licenseNumber: 'License Number',
    licenseCategory: 'License Category',
    uploadPhoto: 'Upload Photo',
    
    // Admin
    totalUsers: 'Total Users',
    testAttempts: 'Test Attempts',
    passRate: 'Pass Rate',
    pendingLicenses: 'Pending Licenses',
    
    // About Page
    aboutTitle: 'About Dereva Kiganjani',
    aboutSubtitle: 'A digital platform by MDV Vehicle Fleet Limited for driver learning, testing, licensing, and recruitment.',
    whoWeAreTitle: 'Who We Are',
    whoWeAreText: 'Dereva Kiganjani is a comprehensive digital platform designed to transform driver services in Tanzania. We provide a seamless experience for driver learning, testing, licensing, and job placement, ensuring safety, professionalism, and efficiency at every step.',
    backedByMDVTitle: 'Backed by MDV Vehicle Fleet',
    backedByMDVText: 'Dereva Kiganjani is a proud program of MDV Vehicle Fleet Limited, a leading transportation and fleet management company in Tanzania.',
    visitMDVWebsite: 'Visit MDV Website',
    whatWeOfferTitle: 'What We Offer',
    elimikaAboutDesc: 'Comprehensive driver education with multimedia courses and progress tracking.',
    jiTestiAboutDesc: 'Professional driver testing with instant results and digital certificates.',
    leseniAboutDesc: 'Streamlined license application and renewal with document tracking.',
    recruitmentLabel: 'Recruitment',
    recruitmentAboutDesc: 'Connect drivers with employers through verified profiles and job matching.',
    impactStatsTitle: 'Our Impact',
    driversTrainedLabel: 'Drivers Trained',
    testsCompletedLabel: 'Tests Completed',
    licensesProcessedLabel: 'Licenses Processed',
    placementsMadeLabel: 'Job Placements',
    exploreServicesTitle: 'Ready to Get Started?',
    exploreServicesText: 'Explore our comprehensive services and join thousands of drivers who trust Dereva Kiganjani.',
    exploreServices: 'Explore Services',
    
    // Services Page
    servicesTitle: 'Our Services',
    servicesSubtitle: 'Comprehensive driver services designed to support your journey from learning to employment.',
    leseniServiceDesc: 'Apply for or renew your driver license with our streamlined digital process.',
    leseniFeature1: 'Online application and renewal',
    leseniFeature2: 'Document upload and verification',
    leseniFeature3: 'Real-time status tracking',
    jiTestiServiceDesc: 'Take professional driver tests for categories A through E with multimedia questions.',
    jiTestiFeature1: 'Multiple-choice questions with images and videos',
    jiTestiFeature2: 'Instant scoring and results',
    jiTestiFeature3: 'Digital certificate upon passing',
    elimikaServiceDesc: 'Access comprehensive driver education courses with various learning materials.',
    elimikaFeature1: 'Text, PDF, and video lessons',
    elimikaFeature2: 'Interactive quizzes and assessments',
    elimikaFeature3: 'Progress tracking and certificates',
    ajiraServiceDesc: 'Create your driver profile and apply for jobs with verified employers.',
    ajiraFeature1: 'Build a professional driver profile',
    ajiraFeature2: 'Browse and apply for job opportunities',
    ajiraFeature3: 'Track application status',
    ajiriServiceDesc: 'Post job openings and hire verified, qualified drivers for your business.',
    ajiriFeature1: 'Post job listings with requirements',
    ajiriFeature2: 'Review driver profiles and applications',
    ajiriFeature3: 'Match with qualified candidates',
    howItWorksTitle: 'How It Works',
    step1Title: 'Create Your Account',
    step1Desc: 'Sign up with your email or phone number to get started with Dereva Kiganjani.',
    step2Title: 'Choose Your Service',
    step2Desc: 'Select from our range of services: testing, learning, licensing, or job opportunities.',
    step3Title: 'Complete Payment',
    step3Desc: 'Pay for applicable services securely through our integrated payment system.',
    step4Title: 'Complete the Process',
    step4Desc: 'Take tests, complete courses, submit applications, or apply for jobs.',
    step5Title: 'Get Results & Notifications',
    step5Desc: 'Receive instant results, certificates, and notifications about your progress.',
    faqTitle: 'Frequently Asked Questions',
    faq1Question: 'How do I register on Dereva Kiganjani?',
    faq1Answer: 'Click on the "Get Started" or "Login" button and create an account using your email or phone number. You will need to complete your profile setup before accessing services.',
    faq2Question: 'What payment methods do you accept?',
    faq2Answer: 'We accept mobile money (M-Pesa, Tigo Pesa, Airtel Money) and bank transfers for all our services.',
    faq3Question: 'How long does it take to process a license request?',
    faq3Answer: 'License processing typically takes 5-10 business days after document verification. You can track your application status in real-time through your dashboard.',
    faq4Question: 'Can I retake a test if I fail?',
    faq4Answer: 'Yes, you can retake the test after 24 hours. Each test attempt requires a separate payment.',
    faq5Question: 'Are the courses certified?',
    faq5Answer: 'Yes, all our learning courses are certified and recognized by relevant authorities. You receive a digital certificate upon successful completion.',
    readyToStartTitle: 'Ready to Get Started?',
    readyToStartText: 'Join thousands of drivers who trust Dereva Kiganjani for their professional development.',
    
    // Contact Page
    contactTitle: 'Contact Us',
    contactSubtitle: 'Get in touch with our team. We\'re here to help you with any questions or concerns.',
    officeAddressLabel: 'Office Address',
    visitByAppointment: 'Visit by appointment only',
    phoneLabel: 'Phone',
    workingHoursLabel: 'Monday - Friday, 8AM - 5PM',
    emailLabel: 'Email',
    supportEmailLabel: 'Support & inquiries',
    officeHoursLabel: 'Office Hours',
    mondayFriday: 'Monday - Friday',
    sendMessageTitle: 'Send us a Message',
    sendMessageDesc: 'Fill out the form below and we\'ll get back to you as soon as possible.',
    namePlaceholder: 'Enter your full name',
    emailPlaceholder: 'your.email@example.com',
    subjectLabel: 'Subject',
    selectSubject: 'Select a subject',
    generalInquiry: 'General Inquiry',
    technicalSupport: 'Technical Support',
    businessPartnership: 'Business Partnership',
    messageLabel: 'Message',
    messagePlaceholder: 'Tell us how we can help you...',
    sendMessage: 'Send Message',
    errorTitle: 'Error',
    fillRequiredFields: 'Please fill in all required fields.',
    messageSentTitle: 'Message Sent!',
    messageSentDesc: 'Thank you for contacting us. We\'ll get back to you soon.',
    whatsappTitle: 'Chat on WhatsApp',
    whatsappDesc: 'Get instant support through our WhatsApp chatbot.',
    whatsappAvailable: 'Available 24/7 for quick questions and support.',
    chatOnWhatsApp: 'Chat on WhatsApp',
    quickLinksLabel: 'Quick Links',
    helpCenterLabel: 'Help Center',
    userGuideLabel: 'User Guide',
    faqLabel: 'FAQ',
    mapPlaceholder: 'Map location placeholder',
    
    // Registration & Auth
    createAccount: 'Create Account',
    registerSubtitle: 'Join Dereva Kiganjani and access all our services',
    accountType: 'Account Type',
    driver: 'Driver',
    driverAccountDesc: 'Access tests, courses, and job opportunities',
    employer: 'Employer',
    employerAccountDesc: 'Post jobs and hire qualified drivers',
    enterFullName: 'Enter your full name',
    optional: 'optional',
    enterEmail: 'Enter your email address',
    password: 'Password',
    enterPassword: 'Enter your password',
    passwordHelper: 'Minimum 8 characters required',
    confirmPassword: 'Confirm Password',
    confirmPasswordPlaceholder: 'Re-enter your password',
    // Employer-specific fields
    companyName: 'Company Name',
    enterCompanyName: 'Enter your company name',
    contactPerson: 'Contact Person',
    enterContactPerson: 'Enter contact person name',
    companyRegistration: 'Company Registration Number',
    enterCompanyRegistration: 'Enter registration number',
    companyAddress: 'Company Address',
    enterCompanyAddress: 'Enter company address',
    companyWebsite: 'Company Website',
    enterCompanyWebsite: 'Enter website URL (e.g., https://example.com)',
    // Driver-specific fields
    nationalIdNumber: 'National ID Number',
    enterNationalId: 'Enter your national ID number',
    agreeToTermsText: 'I agree to the',
    termsAndConditions: 'Terms and Conditions',
    alreadyHaveAccount: 'Already have an account?',
    loginHere: 'Login here',
    verifyPhone: 'Verify Phone Number',
    otpSentToPhone: 'We sent a verification code to your phone',
    enterOtp: 'Enter verification code',
    verify: 'Verify',
    resendOtp: 'Resend Code',
    error: 'Error',
    fillAllRequired: 'Please fill all required fields',
    passwordMismatch: 'Passwords do not match',
    passwordTooShort: 'Password must be at least 8 characters',
    agreeToTerms: 'You must agree to the terms and conditions',
    invalidOtp: 'Please enter a valid 6-digit code',
    success: 'Success',
    accountCreated: 'Account created successfully!',
    forgotPassword: 'Forgot Password',
    forgotPasswordDesc: 'Enter your phone number or email to reset your password',
    checkYourPhone: 'Check Your Phone',
    phoneOrEmail: 'Phone or Email',
    enterPhoneOrEmail: 'Enter your phone number or email',
    sendResetLink: 'Send Reset Link',
    backToLogin: 'Back to Login',
    resetLinkSent: 'Reset link sent successfully',
    resetInstructions: 'Follow the instructions sent to your phone to reset your password',
    resendLink: 'Resend Link',
    resetPassword: 'Reset Password',
    resetPasswordDesc: 'Enter the verification code and your new password',
    verificationCode: 'Verification Code',
    newPassword: 'New Password',
    enterNewPassword: 'Enter your new password',
    passwordReset: 'Password reset successfully!',
    
    // Employer Verification
    accountPendingVerification: 'Account Pending Verification',
    accountPendingVerificationDesc: 'Your employer account is currently under review',
    whatHappensNext: 'What Happens Next?',
    verificationProcessDesc: 'Our team is reviewing your company information and documentation to ensure compliance with our standards.',
    expectedTimeline: 'Expected Timeline',
    verificationTimelineDesc: 'Verification typically takes 1-2 business days. You will receive an email notification once your account is reviewed.',
    emailNotification: 'Email Notification',
    emailNotificationDesc: 'We will send you an email at your registered address once verification is complete.',
    whatWeReReviewing: 'What We\'re Reviewing',
    companyRegistrationDetails: 'Company registration details',
    contactInformation: 'Contact information verification',
    businessLegitimacy: 'Business legitimacy and documentation',
    complianceRequirements: 'Compliance with platform requirements',
    needUrgentHelp: 'Need Urgent Help?',
    urgentHelpDesc: 'If you have questions or need to expedite the verification process, please contact us:',
    viewProfile: 'View Profile',
    verificationInfoNote: 'Please ensure all your company information is accurate and up-to-date. Incomplete or incorrect information may delay the verification process.',
    poweredBy: 'Powered by',
  },
  sw: {
    // Navigation
    home: 'Nyumbani',
    about: 'Kuhusu',
    services: 'Huduma',
    contact: 'Wasiliana',
    login: 'Ingia',
    logout: 'Toka',
    
    // Hero
    heroTitle: 'Kuimarisha Madereva Salama',
    heroSubtitle: 'Karibu Dereva Kiganjani',
    heroDescription: 'Jukwaa lako la huduma za madereva, usimamizi wa leseni, majaribio na kujifunza',
    
    // Services
    leseni: 'Leseni',
    leseniDesc: 'Huduma za Leseni',
    jiTesti: 'JiTesti',
    jiTestiDesc: 'Mtihani wa Udereva',
    elimika: 'Elimika',
    elimikaDesc: 'Kujifunza Udereva',
    ajiraYaUdereva: 'Ajira ya Udereva',
    ajiraDesc: 'Ajira za Madereva',
    ajiriDereva: 'Ajiri Dereva',
    ajiriDesc: 'Ajiri Dereva',
    
    // Common
    getStarted: 'Anza Sasa',
    learnMore: 'Jifunze Zaidi',
    submit: 'Wasilisha',
    cancel: 'Ghairi',
    save: 'Hifadhi',
    continue: 'Endelea',
    back: 'Rudi',
    next: 'Ifuatayo',
    
    // Dashboard
    welcome: 'Karibu',
    dashboard: 'Dashibodi',
    myProfile: 'Wasifu Wangu',
    myResults: 'Matokeo Yangu',
    notifications: 'Arifa',
    recentActivity: 'Shughuli za Hivi Karibuni',
    
    // Test
    startTest: 'Anza Mtihani',
    selectCategory: 'Chagua Aina ya Gari',
    paymentMethod: 'Njia ya Malipo',
    testInProgress: 'Mtihani Unaendelea',
    submitAnswer: 'Wasilisha Jibu',
    correct: 'Sahihi',
    incorrect: 'Si Sahihi',
    passed: 'UMEFAULU',
    failed: 'UMESHINDWA',
    retakeTest: 'Rudia Mtihani',
    downloadCertificate: 'Pakua Cheti',
    
    // Profile
    fullName: 'Jina Kamili',
    phoneNumber: 'Nambari ya Simu',
    nationalId: 'Kitambulisho cha Taifa',
    licenseNumber: 'Nambari ya Leseni',
    licenseCategory: 'Aina ya Leseni',
    uploadPhoto: 'Pakia Picha',
    
    // Admin
    totalUsers: 'Watumiaji Jumla',
    testAttempts: 'Majaribio ya Mtihani',
    passRate: 'Kiwango cha Kufaulu',
    pendingLicenses: 'Leseni Zinazosubiri',
    
    // About Page
    aboutTitle: 'Kuhusu Dereva Kiganjani',
    aboutSubtitle: 'Jukwaa la kidijitali la MDV Vehicle Fleet Limited kwa kujifunza madereva, majaribio, leseni, na uajiri.',
    whoWeAreTitle: 'Sisi ni Nani',
    whoWeAreText: 'Dereva Kiganjani ni jukwaa kamili la kidijitali lililobuniwa kubadilisha huduma za madereva Tanzania. Tunatoa uzoefu wenye ufanisi kwa kujifunza madereva, majaribio, leseni, na mahali pa kazi, kuhakikisha usalama, utaalamu, na ufanisi kila hatua.',
    backedByMDVTitle: 'Imedhaminiwa na MDV Vehicle Fleet',
    backedByMDVText: 'Dereva Kiganjani ni programu yenye fahari ya MDV Vehicle Fleet Limited, kampuni inayoongoza usafiri na usimamizi wa magari Tanzania.',
    visitMDVWebsite: 'Tembelea Tovuti ya MDV',
    whatWeOfferTitle: 'Tunafanya Nini',
    elimikaAboutDesc: 'Elimu kamili ya udereva na kozi za multimedia na ufuatiliaji wa maendeleo.',
    jiTestiAboutDesc: 'Majaribio ya kitaalamu ya udereva na matokeo ya papo hapo na vyeti vya kidijitali.',
    leseniAboutDesc: 'Maombi ya leseni yaliyoboreshwa na upya wa leseni na ufuatiliaji wa nyaraka.',
    recruitmentLabel: 'Uajiri',
    recruitmentAboutDesc: 'Unganisha madereva na waajiri kupitia wasifu uliothhibitishwa na kuoana kwa ajira.',
    impactStatsTitle: 'Athari Yetu',
    driversTrainedLabel: 'Madereva Waliofunzwa',
    testsCompletedLabel: 'Majaribio Yaliyokamilika',
    licensesProcessedLabel: 'Leseni Zilizosindikwa',
    placementsMadeLabel: 'Mahali pa Kazi',
    exploreServicesTitle: 'Tayari Kuanza?',
    exploreServicesText: 'Gundua huduma zetu kamili na ujiunge na maelfu ya madereva wanaoamini Dereva Kiganjani.',
    exploreServices: 'Gundua Huduma',
    
    // Services Page
    servicesTitle: 'Huduma Zetu',
    servicesSubtitle: 'Huduma kamili za madereva zilizoundwa kusaidia safari yako kutoka kujifunza hadi ajira.',
    leseniServiceDesc: 'Omba au upya leseni yako ya udereva na mchakato wetu ulioboreshwa wa kidijitali.',
    leseniFeature1: 'Maombi na upya ya mtandaoni',
    leseniFeature2: 'Upakiaji na uthibitishaji wa nyaraka',
    leseniFeature3: 'Ufuatiliaji wa hali ya wakati halisi',
    jiTestiServiceDesc: 'Fanya majaribio ya kitaalamu ya madereva kwa makundi A hadi E na maswali ya multimedia.',
    jiTestiFeature1: 'Maswali ya chaguo-nyingi yenye picha na video',
    jiTestiFeature2: 'Uchunguzi wa papo hapo na matokeo',
    jiTestiFeature3: 'Cheti cha kidijitali baada ya kufaulu',
    elimikaServiceDesc: 'Pata kozi kamili za elimu ya udereva na vifaa mbalimbali vya kujifunza.',
    elimikaFeature1: 'Masomo ya maandishi, PDF, na video',
    elimikaFeature2: 'Majaribio ya maingiliano na tathmini',
    elimikaFeature3: 'Ufuatiliaji wa maendeleo na vyeti',
    ajiraServiceDesc: 'Unda wasifu wako wa udereva na omba ajira na waajiri waliothhibitishwa.',
    ajiraFeature1: 'Jenga wasifu wa kitaalamu wa udereva',
    ajiraFeature2: 'Vinjari na omba fursa za ajira',
    ajiraFeature3: 'Fuatilia hali ya maombi',
    ajiriServiceDesc: 'Chapisha nafasi za kazi na uajiri madereva waliothhibitishwa, wenye sifa kwa biashara yako.',
    ajiriFeature1: 'Chapisha orodha za ajira na mahitaji',
    ajiriFeature2: 'Kagua wasifu wa madereva na maombi',
    ajiriFeature3: 'Oana na wagombea wenye sifa',
    howItWorksTitle: 'Inafanyaje Kazi',
    step1Title: 'Unda Akaunti Yako',
    step1Desc: 'Jisajili kwa barua pepe yako au nambari ya simu ili uanze na Dereva Kiganjani.',
    step2Title: 'Chagua Huduma Yako',
    step2Desc: 'Chagua kutoka kwa huduma zetu: majaribio, kujifunza, leseni, au fursa za ajira.',
    step3Title: 'Maliza Malipo',
    step3Desc: 'Lipia huduma zinazohusika kwa usalama kupitia mfumo wetu uliopatanishwa wa malipo.',
    step4Title: 'Maliza Mchakato',
    step4Desc: 'Fanya majaribio, maliza kozi, wasilisha maombi, au omba ajira.',
    step5Title: 'Pata Matokeo na Arifa',
    step5Desc: 'Pokea matokeo ya papo hapo, vyeti, na arifa kuhusu maendeleo yako.',
    faqTitle: 'Maswali Yanayoulizwa Mara Kwa Mara',
    faq1Question: 'Ninajisajili vipi kwenye Dereva Kiganjani?',
    faq1Answer: 'Bonyeza kitufe cha "Anza Sasa" au "Ingia" na unda akaunti kwa kutumia barua pepe yako au nambari ya simu. Utahitaji kukamilisha usanidi wa wasifu wako kabla ya kupata huduma.',
    faq2Question: 'Mnakubali njia gani za malipo?',
    faq2Answer: 'Tunakubali pesa za simu (M-Pesa, Tigo Pesa, Airtel Money) na uhamisho wa benki kwa huduma zetu zote.',
    faq3Question: 'Inachukua muda gani kusindika ombi la leseni?',
    faq3Answer: 'Usindikaji wa leseni kawaida unachukua siku 5-10 za biashara baada ya uthibitishaji wa nyaraka. Unaweza kufuatilia hali ya maombi yako wakati halisi kupitia dashibodi yako.',
    faq4Question: 'Naweza kufanya tena mtihani kama nitashindwa?',
    faq4Answer: 'Ndiyo, unaweza kurudia mtihani baada ya masaa 24. Kila jaribio la mtihani linahitaji malipo tofauti.',
    faq5Question: 'Je, kozi zina vyeti?',
    faq5Answer: 'Ndiyo, kozi zetu zote za kujifunza zina vyeti na zinatambuliwa na mamlaka husika. Unapokea cheti cha kidijitali baada ya kukamilisha kwa mafanikio.',
    readyToStartTitle: 'Tayari Kuanza?',
    readyToStartText: 'Jiunge na maelfu ya madereva wanaoamini Dereva Kiganjani kwa maendeleo yao ya kitaalamu.',
    
    // Contact Page
    contactTitle: 'Wasiliana Nasi',
    contactSubtitle: 'Wasiliana na timu yetu. Tuko hapa kukusaidia na maswali au wasiwasi wowote.',
    officeAddressLabel: 'Anwani ya Ofisi',
    visitByAppointment: 'Tembelea kwa miadi tu',
    phoneLabel: 'Simu',
    workingHoursLabel: 'Jumatatu - Ijumaa, 8AM - 5PM',
    emailLabel: 'Barua Pepe',
    supportEmailLabel: 'Msaada na maswali',
    officeHoursLabel: 'Masaa ya Ofisi',
    mondayFriday: 'Jumatatu - Ijumaa',
    sendMessageTitle: 'Tutumie Ujumbe',
    sendMessageDesc: 'Jaza fomu hapa chini na tutawasiliana nawe haraka iwezekanavyo.',
    namePlaceholder: 'Weka jina lako kamili',
    emailPlaceholder: 'barua.pepe@mfano.com',
    subjectLabel: 'Mada',
    selectSubject: 'Chagua mada',
    generalInquiry: 'Swali la Jumla',
    technicalSupport: 'Msaada wa Kiufundi',
    businessPartnership: 'Ushirikiano wa Biashara',
    messageLabel: 'Ujumbe',
    messagePlaceholder: 'Tuambie jinsi tunavyoweza kukusaidia...',
    sendMessage: 'Tuma Ujumbe',
    errorTitle: 'Hitilafu',
    fillRequiredFields: 'Tafadhali jaza sehemu zote zinazohitajika.',
    messageSentTitle: 'Ujumbe Umetumwa!',
    messageSentDesc: 'Asante kwa kuwasiliana nasi. Tutawasiliana nawe hivi karibuni.',
    whatsappTitle: 'Ongea kwenye WhatsApp',
    whatsappDesc: 'Pata msaada wa papo hapo kupitia chatbot yetu ya WhatsApp.',
    whatsappAvailable: 'Inapatikana 24/7 kwa maswali ya haraka na msaada.',
    chatOnWhatsApp: 'Ongea kwenye WhatsApp',
    quickLinksLabel: 'Viungo vya Haraka',
    helpCenterLabel: 'Kituo cha Msaada',
    userGuideLabel: 'Mwongozo wa Mtumiaji',
    faqLabel: 'Maswali Mara Kwa Mara',
    mapPlaceholder: 'Mahali pa ramani',
    
    // Registration & Auth
    createAccount: 'Unda Akaunti',
    registerSubtitle: 'Jiunge na Dereva Kiganjani na pata huduma zetu zote',
    accountType: 'Aina ya Akaunti',
    driver: 'Dereva',
    driverAccountDesc: 'Pata majaribio, kozi, na fursa za ajira',
    employer: 'Mwajiri',
    employerAccountDesc: 'Chapisha ajira na uajiri madereva wenye sifa',
    enterFullName: 'Weka jina lako kamili',
    optional: 'si lazima',
    enterEmail: 'Weka anwani yako ya barua pepe',
    password: 'Neno la Siri',
    enterPassword: 'Weka neno lako la siri',
    passwordHelper: 'Herufi 8 au zaidi zinahitajika',
    confirmPassword: 'Thibitisha Neno la Siri',
    confirmPasswordPlaceholder: 'Weka tena neno lako la siri',
    // Employer-specific fields
    companyName: 'Jina la Kampuni',
    enterCompanyName: 'Weka jina la kampuni yako',
    contactPerson: 'Mtu wa Kuwasiliana',
    enterContactPerson: 'Weka jina la mtu wa kuwasiliana',
    companyRegistration: 'Nambari ya Usajili wa Kampuni',
    enterCompanyRegistration: 'Weka nambari ya usajili',
    companyAddress: 'Anwani ya Kampuni',
    enterCompanyAddress: 'Weka anwani ya kampuni',
    companyWebsite: 'Tovuti ya Kampuni',
    enterCompanyWebsite: 'Weka URL ya tovuti (mfano, https://example.com)',
    // Driver-specific fields
    nationalIdNumber: 'Nambari ya Kitambulisho cha Taifa',
    enterNationalId: 'Weka nambari yako ya kitambulisho cha taifa',
    agreeToTermsText: 'Ninakubali',
    termsAndConditions: 'Sheria na Masharti',
    alreadyHaveAccount: 'Tayari una akaunti?',
    loginHere: 'Ingia hapa',
    verifyPhone: 'Thibitisha Nambari ya Simu',
    otpSentToPhone: 'Tumetuma nambari ya uthibitishaji kwa simu yako',
    enterOtp: 'Weka nambari ya uthibitishaji',
    verify: 'Thibitisha',
    resendOtp: 'Tuma Tena Nambari',
    error: 'Hitilafu',
    fillAllRequired: 'Tafadhali jaza sehemu zote zinazohitajika',
    passwordMismatch: 'Maneno ya siri hayalingani',
    passwordTooShort: 'Neno la siri lazima liwe na herufi 8 au zaidi',
    agreeToTerms: 'Lazima ukubali sheria na masharti',
    invalidOtp: 'Tafadhali weka nambari sahihi ya tarakimu 6',
    success: 'Mafanikio',
    accountCreated: 'Akaunti imeundwa kwa mafanikio!',
    forgotPassword: 'Umesahau Neno la Siri',
    forgotPasswordDesc: 'Weka nambari yako ya simu au barua pepe kurekebisha neno lako la siri',
    checkYourPhone: 'Angalia Simu Yako',
    phoneOrEmail: 'Simu au Barua Pepe',
    enterPhoneOrEmail: 'Weka nambari yako ya simu au barua pepe',
    sendResetLink: 'Tuma Kiungo cha Kurekebisha',
    backToLogin: 'Rudi kwenye Kuingia',
    resetLinkSent: 'Kiungo cha kurekebisha kimetumwa kwa mafanikio',
    resetInstructions: 'Fuata maelekezo yaliyotumwa kwa simu yako kurekebisha neno lako la siri',
    resendLink: 'Tuma Tena Kiungo',
    resetPassword: 'Rekebisha Neno la Siri',
    resetPasswordDesc: 'Weka nambari ya uthibitishaji na neno lako jipya la siri',
    verificationCode: 'Nambari ya Uthibitishaji',
    newPassword: 'Neno Jipya la Siri',
    enterNewPassword: 'Weka neno lako jipya la siri',
    passwordReset: 'Neno la siri limerekebishwa kwa mafanikio!',
    
    // Employer Verification
    accountPendingVerification: 'Akaunti Inasubiri Uthibitishaji',
    accountPendingVerificationDesc: 'Akaunti yako ya mwajiri inakaguliwa',
    whatHappensNext: 'Nini Kinachofuata?',
    verificationProcessDesc: 'Timu yetu inakagua taarifa za kampuni yako na nyaraka kuhakikisha kufuata viwango vyetu.',
    expectedTimeline: 'Muda Unaotarajiwa',
    verificationTimelineDesc: 'Uthibitishaji kawaida unachukua siku 1-2 za biashara. Utapokea arifa ya barua pepe mara akaunti yako itakapokaguliwa.',
    emailNotification: 'Arifa ya Barua Pepe',
    emailNotificationDesc: 'Tutakutumia barua pepe kwenye anwani yako iliyosajiliwa mara uthibitishaji utakapokamilika.',
    whatWeReReviewing: 'Tunachokagua',
    companyRegistrationDetails: 'Maelezo ya usajili wa kampuni',
    contactInformation: 'Uthibitishaji wa taarifa za mawasiliano',
    businessLegitimacy: 'Uhalali wa biashara na nyaraka',
    complianceRequirements: 'Kufuata mahitaji ya jukwaa',
    needUrgentHelp: 'Unahitaji Msaada wa Haraka?',
    urgentHelpDesc: 'Ikiwa una maswali au unahitaji kuharakisha mchakato wa uthibitishaji, tafadhali wasiliana nasi:',
    viewProfile: 'Angalia Wasifu',
    verificationInfoNote: 'Tafadhali hakikisha taarifa zote za kampuni yako ni sahihi na za kisasa. Taarifa zisizokamilika au zisizo sahihi zinaweza kucheleza mchakato wa uthibitishaji.',
    poweredBy: 'Inaendeshwa na',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  // Initialize language from localStorage or default to 'en'
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved === 'en' || saved === 'sw') ? saved : 'en';
  });

  // Persist language choice to localStorage
  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
